### ISSUE TITLE
repo guidance request.

### ISSUE THREAD

**Issue by seghers** [pimeys/nixos#3]
Dear

I'm currently running Nixos(native encrypted zfs mirror) gnome3 without flakes. Your repo's layout looks nice and simple enough to get started with flakes, home-manager and sway.

I have a few questions about your repo.

In your ".gitignore" there are 2 files:
https://github.com/pimeys/nixos/blob/9f99d4f90235187ec45f29b30815cfc0529ec829/.gitignore#L1-L2

**_What is inside these?_**
Or is "configuration.nix" just a copy/rename/link of "hosts/meowmeow.nix".
Is your "file-systems.nix" a deprecated?/?old file and currently integrated in "hosts/meowmeow.nix"
https://github.co_**How do you do the secret management?**_m/pimeys/nixos/blob/9f99d4f90235187ec45f29b30815cfc0529ec829/hosts/meowmeow.nix#L57-L70

_**How do you do the secret management?**_
- Local submodule repo?
- agenix, git-crypt, sops-nix,...?

Thanks for reading.

**Comment by pimeys** [comment]
Hey! I'm also JUST STARTING with nixos and kind of finally understood the flakes, I've used flakes now a bit over a month... I'm probably refactoring this repo soon to be neat and clean, but let me try to answer:

The gitignore is from the time before flakes. I should remove that.

Secret management is a local NAS box (FreeBSD) at home. I clone the files from there and source the variables when starting a sway session. It's just one file with `export KEY=val` kind of syntax. And contains some home secrets that are not that important if they leak, but still better to just hold out from this git repo.

Agenix didn't work for me because it'll create the files when you `switch`. The files get deleted on boot and you cannot read them to your NixOS configuration due to being not allowed in flakes. So, I just in the end did the easiest setup: secret private repo with files, update the submodule, evaluate when starting a desktop session.

Hopefully this repo is helping you out. I did just the same: browsed other people's repos trying to understand how flakes work. It takes a while, but I think at least for me has been worth the investment.
